### ISSUE TITLE
Add initializer for injecting configuration. 

### ISSUE THREAD

**Issue by markohlebar** [urbanairship/ios-segment-integration#13]
Hi guys, we are looking at using segment - airship integration. Our project has 3 different environments dev/test/prod, and for that we're using 3 different `AirshipConfig.plist` files. 

Currently we're initializing Airship like so:
```
        let config = UAConfig(contentsOfFile: filePath)
        UAirship.takeOff(config)
```

We're suggesting an addition to `SEGUrbanAirshipIntegrationFactory`, where you can pass in the desired configuration. Similar to what `AppsFlyer` is doing with [their integration](https://github.com/AppsFlyerSDK/segment-appsflyer-ios/blob/master/segment-appsflyer-ios/Classes/SEGAppsFlyerIntegrationFactory.h).

**Comment by BrianBatchelder** [comment]
Thanks for the suggestion, @markohlebar. We'll look into it.
