### ISSUE TITLE
Process hanging

### ISSUE THREAD

**Issue by ihorzabrotsky** [urbanairship/ios-segment-integration#3]
Hello, guys!
Today I faced a problem with Segment: when I move to Safari from my app and then tap "Back to app" my app doesn't response because of this:
![seganalyticshanging](https://cloud.githubusercontent.com/assets/11959312/18058037/35e9d8e6-6e1b-11e6-9c9a-acdcf8b6caa4.png)
and when I click on the row which has "5" at a start in stack trace I am redirected to 
 `- (void)forwardSelector:(SEL)selector arguments:(NSArray *)arguments options:(NSDictionary *)options`
method to 
`@synchronized(self)`
line. As I suspect this is the result of application's lifecycle tracking by Segment (it receives notifications when application changes it's state) but I can't switch it off because both Adjust and Flurry don't allow me to update Segment to 3.1.0 version (current is 3.0.7).
I have already fixed this by replacing that line to
`dispatch_async(dispatch_get_main_queue, ^{ ... });`
but the problem is that we don't commit pods and generally we don't fix anything in pods (that's bad practise, of course).
Do you have an idea how to resolve this issue?

**Comment by rlepinski** [comment]
@ihorzabrotsky Sorry, just seeing this issue. Where you able to resolve the problem? Is it a problem with the UAirship integration or segment directly?

**Comment by rlepinski** [comment]
Closing for now. Please reopen if you still having issues.
